name: C/C++ CI with Bazel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        bazelisk-version: '1.27.0'
        bazelisk-cache: 'true'
        disk-cache: 'true'
        repository-cache: 'true'
      env:
        PYTHON_BIN_PATH: ${{ env.pythonLocation }}/bin/python

    - name: Build all targets
      run: bazel build //... --config=unix
    
    - name: Test all targets
      run: bazel test //... --config=unix

    - name: Build Python extension with Bazel
      shell: bash
      run: |
        bazel build //python:my_robot_py

    - name: Run pytest
      shell: bash
      run: |
        set -euo pipefail
        pip install -q pytest

        BAZEL_BIN="$(bazel info bazel-bin)"
        mkdir -p python/src/my_robot_py/
        SRC="${BAZEL_BIN}/python/my_robot_py.so"
        if [[ ! -f "$SRC" ]]; then
          echo "Expected artifact not found: $SRC"
          echo "Bazel output tree (first 200 files under bazel-bin):"
          find "$BAZEL_BIN" -type f | sed "s|^${BAZEL_BIN}/||" | head -n 200
          exit 1
        fi
        cp "$SRC" python/src/my_robot_py/

        # Safe even when PYTHONPATH is not set (works with 'set -u')
        export PYTHONPATH="$(pwd)/python/src${PYTHONPATH:+:$PYTHONPATH}"
        pytest -q tests/python

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format check (placeholder)
        run: |
          # Placeholder for clang-format check
          echo "Clang-format check would run here."
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run ruff check (placeholder)
        run: |
          # Placeholder for ruff check
          echo "Ruff check would run here."