name: C/C++ CI with Bazel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        bazelisk-version: '1.27.0'
        bazelisk-cache: 'true'
        disk-cache: 'true'
        repository-cache: 'true'
      env:
        PYTHON_BIN_PATH: ${{ env.pythonLocation }}/bin/python

    - name: Build on Windows (hardened + scan for bad paths)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"

        # ----- Stable absolute roots -----
        $drive = (Get-Location).Path.Substring(0,2)   # e.g. 'D:'
        $ROOT  = "$drive/bzl" -replace '\\','/'
        New-Item -ItemType Directory -Force -Path "$ROOT/tmp","$ROOT/home","$ROOT/out" | Out-Null

        # ----- Clean/process-local env -----
        $env:TMP         = "$ROOT/tmp"
        $env:TEMP        = "$ROOT/tmp"
        $env:TEST_TMPDIR = "$ROOT/tmp"
        $env:HOME        = "$ROOT/home"
        $env:USERPROFILE = "$ROOT/home"

        # Scrub bazel-specific startup envs
        foreach ($k in 'BAZEL_OUTPUT_USER_ROOT','BAZEL_OUTPUT_BASE') {
          [Environment]::SetEnvironmentVariable($k,$null,'Process')
        }

        # Find ANY env var that is exactly "\" or "/" and clear it (common culprit)
        $badVals = @('\','/')
        $sus = gci env: | ? { $badVals -contains $_.Value }
        foreach ($e in $sus) {
          Write-Host "Clearing suspicious env: $($e.Name)='$($e.Value)'"
          [Environment]::SetEnvironmentVariable($e.Name,$null,'Process')
        }

        # ----- Quick static scan of repo for Windows-bad absolute roots -----
        # Looks for:
        #  - local_repository/new_local_repository path = "\" or "/"
        #  - bzlmod local_path_override(..., path = "\" or "/")
        #  - .bazelrc startup/build flags that set output_* or install_base to "\" or "/"
        $patterns = @(
          'local_repository\s*\([^)]*path\s*=\s*["'']\\["'']',
          'local_repository\s*\([^)]*path\s*=\s*["'']\/["'']',
          'new_local_repository\s*\([^)]*path\s*=\s*["'']\\["'']',
          'new_local_repository\s*\([^)]*path\s*=\s*["'']\/["'']',
          'local_path_override\s*\([^)]*path\s*=\s*["'']\\["'']',
          'local_path_override\s*\([^)]*path\s*=\s*["'']\/["'']',
          'startup\s+--(output_user_root|output_base|install_base)\s*=\s*[\\/]$',
          'build\s+--(output_user_root|output_base|install_base)\s*=\s*[\\/]$'
        )
        $hits = @()
        foreach ($p in $patterns) {
          $hits += Select-String -Path @(".bazelrc","WORKSPACE","WORKSPACE.bzl","MODULE.bazel","**/*.bzl","**/BUILD","**/BUILD.bazel") -Pattern $p -AllMatches -ErrorAction SilentlyContinue
        }
        if ($hits.Count -gt 0) {
          Write-Host "=== Suspicious path settings detected ==="
          $hits | % { "$($_.Path):$($_.LineNumber): $($_.Line)" } | Sort-Object -Unique | ForEach-Object { Write-Host $_ }
          Write-Host "========================================="
        }

        # ----- Start from a clean Bazel server with pinned roots -----
        bazel --ignore_all_rc_files --nowatchfs `
              --output_user_root=$ROOT --output_base=$ROOT/out shutdown

        # Info (should show D:/bzl/out etc.)
        bazel --ignore_all_rc_files --nowatchfs `
              --output_user_root=$ROOT --output_base=$ROOT/out info output_base

        # Build & test (pipe logs to files for artifact upload)
        bazel --ignore_all_rc_files --nowatchfs `
              --output_user_root=$ROOT --output_base=$ROOT/out `
              build //... --verbose_failures --show_timestamps 2>&1 | Tee-Object -FilePath bazel-build.log

        bazel --ignore_all_rc_files --nowatchfs `
              --output_user_root=$ROOT --output_base=$ROOT/out `
              test //... --verbose_failures --show_timestamps 2>&1 | Tee-Object -FilePath bazel-test.log

        # Dump env for post-mortem
        Write-Host "`n=== Path env dump ==="
        gci env: | ? { $_.Name -match 'BAZEL|TEST_TMPDIR|^TMP$|^TEMP$|^HOME$|USERPROFILE|HOMEDRIVE|HOMEPATH' } | sort Name | ft -AutoSize

    - name: Build all targets (Unix)
      if: matrix.os != 'windows-latest'
      run: bazel build //... --config=unix
    
    - name: Test all targets (Unix)
      if: matrix.os != 'windows-latest'
      run: bazel test //... --config=unix
    
    - name: Install Python dependencies and run Python tests
      shell: bash
      run: |
        pip install pytest
        # Copy the Bazel-built extension to the Python package location
        mkdir -p python/src/my_robot_py/
        cp bazel-bin/python/my_robot_py.so python/src/my_robot_py/
        # Add the python directory to PYTHONPATH so tests can find the module
        export PYTHONPATH="${PYTHONPATH}:$(pwd)/python/src"
        pytest tests/python

    - name: Upload Windows logs
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-debug-logs-${{ github.run_id }}
        path: |
          bazel-build.log
          bazel-test.log
          bazel-info.log
        retention-days: 7

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format check (placeholder)
        run: |
          # Placeholder for clang-format check
          echo "Clang-format check would run here."
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run ruff check (placeholder)
        run: |
          # Placeholder for ruff check
          echo "Ruff check would run here."