name: C/C++ CI with Bazel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        bazelisk-version: '1.27.0'
        bazelisk-cache: 'true'
        disk-cache: 'true'
        repository-cache: 'true'
      env:
        PYTHON_BIN_PATH: ${{ env.pythonLocation }}/bin/python

    - name: Build on Windows (hardened)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"

        # Short absolute root on the current drive (GitHub runners: D:)
        $drive = (Get-Location).Path.Substring(0,2)    # e.g. 'D:'
        $ROOT  = "$drive/bzl" -replace '\\','/'
        New-Item -ItemType Directory -Force -Path "$ROOT/tmp","$ROOT/home","$ROOT/out" | Out-Null

        # Hard-set path envs to absolute values (don't rely on runner defaults)
        $env:TMP         = "$ROOT/tmp"
        $env:TEMP        = "$ROOT/tmp"
        $env:HOME        = "$ROOT/home"
        $env:TEST_TMPDIR = "$ROOT/tmp"
        $env:HOMEDRIVE   = $drive
        $env:HOMEPATH    = "/bzl/home"
        $env:USERPROFILE = "$ROOT/home"

        # Scrub Bazel path envs that, if '\' or empty, poison the server
        foreach ($k in 'BAZEL_OUTPUT_USER_ROOT','BAZEL_OUTPUT_BASE') {
          [Environment]::SetEnvironmentVariable($k,$null,'Process')
        }

        # If your repo .bazelrc has bad startup paths, neutralize them in-process
        $rcPath = Join-Path (Get-Location) ".bazelrc"
        if (Test-Path $rcPath) {
          $rc = Get-Content $rcPath -Raw
          $rc = $rc -replace 'startup\s+--output_user_root\s*=\s*[\\/]\s*', "startup --output_user_root=$ROOT`n"
          $rc = $rc -replace 'startup\s+--output_base\s*=\s*[\\/]\s*',       "startup --output_base=$ROOT/out`n"
          Set-Content -NoNewline -Path $rcPath -Value $rc
        }

        # Ensure no server is running with different roots
        bazel --output_user_root=$ROOT --output_base=$ROOT/out shutdown

        # Build with startup opts (keep these on EVERY bazel call in this step)
        bazel --output_user_root=$ROOT --output_base=$ROOT/out info output_base
        bazel --output_user_root=$ROOT --output_base=$ROOT/out build //... --verbose_failures --show_timestamps
        bazel --output_user_root=$ROOT --output_base=$ROOT/out test //... --verbose_failures --show_timestamps

        Write-Host "`n=== Path env dump ==="
        gci env: | ? { $_.Name -match 'BAZEL|TEST_TMPDIR|^TMP$|^TEMP$|^HOME$|HOMEDRIVE|HOMEPATH|USERPROFILE' } | sort Name | ft -AutoSize

    - name: Test all targets (Unix)
      if: matrix.os != 'windows-latest'
      run: bazel test //... --config=unix
    
    - name: Install Python dependencies and run Python tests
      shell: bash
      run: |
        pip install pytest
        # Copy the Bazel-built extension to the Python package location
        mkdir -p python/src/my_robot_py/
        cp bazel-bin/python/my_robot_py.so python/src/my_robot_py/
        # Add the python directory to PYTHONPATH so tests can find the module
        export PYTHONPATH="${PYTHONPATH}:$(pwd)/python/src"
        pytest tests/python

    - name: Upload debug logs (Windows only)
      if: matrix.os == 'windows-latest' && failure()
      uses: actions/upload-artifact@v4
      with:
        name: windows-debug-logs-${{ github.run_id }}
        path: |
          bazel-build.log
        retention-days: 7

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format check (placeholder)
        run: |
          # Placeholder for clang-format check
          echo "Clang-format check would run here."
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run ruff check (placeholder)
        run: |
          # Placeholder for ruff check
          echo "Ruff check would run here."
