name: C/C++ CI with Bazel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        bazelisk-version: '1.27.0'
        bazelisk-cache: 'true'
        disk-cache: 'true'
        repository-cache: 'true'
      env:
        PYTHON_BIN_PATH: ${{ env.pythonLocation }}/bin/python

    - name: Build on Windows (rc-free, pinned paths)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"

        $drive = (Get-Location).Path.Substring(0,2)   # e.g. 'D:'
        $ROOT  = "$drive/bzl" -replace '\\','/'
        New-Item -ItemType Directory -Force -Path "$ROOT/tmp","$ROOT/home","$ROOT/out" | Out-Null

        # Absolute, sane dirs (do NOT touch HOMEDRIVE/HOMEPATH)
        $env:TMP         = "$ROOT/tmp"
        $env:TEMP        = "$ROOT/tmp"
        $env:TEST_TMPDIR = "$ROOT/tmp"
        $env:HOME        = "$ROOT/home"
        $env:USERPROFILE = "$ROOT/home"

        # Scrub Bazel-specific startup envs
        foreach ($k in 'BAZEL_OUTPUT_USER_ROOT','BAZEL_OUTPUT_BASE') {
          [Environment]::SetEnvironmentVariable($k,$null,'Process')
        }

        # Kill any server started with different env/roots
        bazel --ignore_all_rc_files shutdown

        # All bazel invocations in THIS step must carry the same startup flags
        bazel --ignore_all_rc_files --output_user_root=$ROOT --output_base=$ROOT/out info output_base

        bazel --ignore_all_rc_files --output_user_root=$ROOT --output_base=$ROOT/out `
              build //... --verbose_failures --show_timestamps 2>&1 | Tee-Object -FilePath bazel-build.log

        bazel --ignore_all_rc_files --output_user_root=$ROOT --output_base=$ROOT/out `
              test //... --verbose_failures --show_timestamps 2>&1 | Tee-Object -FilePath bazel-test.log

        # Extra debug info to verify rc and temp settings
        bazel --ignore_all_rc_files --output_user_root=$ROOT --output_base=$ROOT/out info 2>&1 | Tee-Object -FilePath bazel-info.log

        Write-Host "`n=== Path env dump ==="
        gci env: | ? { $_.Name -match 'BAZEL|TEST_TMPDIR|^TMP$|^TEMP$|^HOME$|USERPROFILE|HOMEDRIVE|HOMEPATH' } | sort Name | ft -AutoSize

    - name: Build all targets (Unix)
      if: matrix.os != 'windows-latest'
      run: bazel build //... --config=unix
    
    - name: Test all targets (Unix)
      if: matrix.os != 'windows-latest'
      run: bazel test //... --config=unix
    
    - name: Install Python dependencies and run Python tests
      shell: bash
      run: |
        pip install pytest
        # Copy the Bazel-built extension to the Python package location
        mkdir -p python/src/my_robot_py/
        cp bazel-bin/python/my_robot_py.so python/src/my_robot_py/
        # Add the python directory to PYTHONPATH so tests can find the module
        export PYTHONPATH="${PYTHONPATH}:$(pwd)/python/src"
        pytest tests/python

    - name: Upload Windows logs
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-debug-logs-${{ github.run_id }}
        path: |
          bazel-build.log
          bazel-test.log
          bazel-info.log
        retention-days: 7

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format check (placeholder)
        run: |
          # Placeholder for clang-format check
          echo "Clang-format check would run here."
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run ruff check (placeholder)
        run: |
          # Placeholder for ruff check
          echo "Ruff check would run here."