name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/my_robot_py
    permissions:
      id-token: write

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: pip install scikit-build-core pybind11

      - name: Build Python wheel and sdist
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  cpp-release:
    name: Build and release C++ artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Download and install MuJoCo
        run: |
          # This is a placeholder for downloading and installing MuJoCo.
          mkdir -p $HOME/mujoco
          echo "CMAKE_PREFIX_PATH=$HOME/mujoco" >> $GITHUB_ENV

      - name: Configure and build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Create C++ release archive
        run: |
          mkdir -p staging
          if [ "$RUNNER_OS" == "Linux" ]; then
            cp build/apps/my_app/my_app staging/
            tar -czvf my_robot_project-${{ github.ref_name }}-${{ matrix.os }}.tar.gz -C staging .
          elif [ "$RUNNER_OS" == "Windows" ]; then
            cp build/apps/my_app/Release/my_app.exe staging/
            7z a my_robot_project-${{ github.ref_name }}-${{ matrix.os }}.zip ./staging/*
          elif [ "$RUNNER_OS" == "macOS" ]; then
            cp build/apps/my_app/my_app staging/
            zip -r my_robot_project-${{ github.ref_name }}-${{ matrix.os }}.zip staging
          fi
        
      - name: Upload C++ artifact to GitHub Release
        uses: actions/upload-release-artifact@v3
        with:
          path: |
            my_robot_project-*.tar.gz
            my_robot_project-*.zip
