name: Release with Bazel

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/my_robot_py
    permissions:
      id-token: write

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@v0.15.0
        with:
          bazelisk-version: 'v1.27.0'
          bazelisk-cache: 'true'
          disk-cache: 'true'
          repository-cache: 'true'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: pip install setuptools wheel

      - name: Build Python wheel and sdist
        run: python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  cpp-release:
    name: Build and release C++ artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@v0.15.0
        with:
          bazelisk-version: 'v1.27.0'
          bazelisk-cache: 'true'
          disk-cache: 'true'
          repository-cache: 'true'
      
      - name: Build C++ artifacts
        run: bazel build //apps/my_app:my_app --compilation_mode=opt

      - name: Create C++ release archive
        shell: bash
        run: |
          mkdir -p staging
          if [ "$RUNNER_OS" == "Linux" ]; then
            cp bazel-bin/apps/my_app/my_app staging/
            tar -czvf my_robot_project-${{ github.ref_name }}-${{ matrix.os }}.tar.gz -C staging .
          elif [ "$RUNNER_OS" == "Windows" ]; then
            cp bazel-bin/apps/my_app/my_app.exe staging/
            7z a my_robot_project-${{ github.ref_name }}-${{ matrix.os }}.zip ./staging/*
          elif [ "$RUNNER_OS" == "macOS" ]; then
            cp bazel-bin/apps/my_app/my_app staging/
            zip -r my_robot_project-${{ github.ref_name }}-${{ matrix.os }}.zip staging
          fi
        
      - name: Upload C++ artifact to GitHub Release
        uses: actions/upload-release-artifact@v3
        with:
          path: |
            my_robot_project-*.tar.gz
            my_robot_project-*.zip
