name: Release with Bazel

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/my_robot_py
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-version: '1.27.0'
          bazelisk-cache: 'true'
          disk-cache: 'true'
          repository-cache: 'true'

      - name: Install build dependencies
        run: pip install setuptools wheel

      - name: Build Python wheel and sdist
        run: python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  cpp-release:
    name: Build and release C++ artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-version: '1.27.0'
          bazelisk-cache: 'true'
          disk-cache: 'true'
          repository-cache: 'true'
      
      - name: Build C++ artifacts
        run: bazel build //apps/my_app:my_app --compilation_mode=opt

      - name: Create C++ release archive
        shell: bash
        run: |
          mkdir -p staging
          cp bazel-bin/apps/my_app/my_app staging/
          tar -czvf my_robot_project-${{ github.ref_name }}-${{ matrix.os }}.tar.gz -C staging .
        
      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: my_robot_project-*.tar.gz
          fail_on_unmatched_files: true